In [3]:
import pandas as pd
import numpy as np

In [30]:
dataset=pd.read_csv('./datapegawai3.csv')
dataset 

Kota  Umur  MasaKerja   Gaji Bonus
0   Surabaya  27.0          9  51000   Yes
1    Jakarta  29.0          9  48000   Yes
2   Surabaya  30.0          5  52000    No
3    Jakarta  25.0          5  66000    No
4     Kediri  48.0         10  68000   Yes
5     Kediri  33.0          8  51000    No
6     Malang  33.0          9  69000    No
7    Jakarta  40.0         10  79000   Yes
8   Surabaya  38.0          8  68000   Yes
9     Malang  35.0          8  38000    No
10    Kediri  28.0          8  56000    No
11    Malang  35.0          8  72000    No
12   Jakarta  36.5         12  79000   Yes
13  Surabaya  31.0          8  85000    No
14    Malang  37.0          6  49000    No
15  Surabaya  40.0         11  69000   Yes
16    Kediri  50.0          8  68000   Yes
17  Surabaya  31.0          8  68000    No
18  Surabaya  36.5          4  68000   Yes
19    Kediri  41.0          6  75000   Yes
20    Kediri  29.0          8  70000    No

In [36]:
x=dataset.iloc[:,:4].values
y=dataset.iloc[:,-1].values
y

array(['Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes',
       'No'], dtype=object)

In [32]:
pd.unique(dataset['Kota'])

array(['Surabaya', 'Jakarta', 'Kediri', 'Malang'], dtype=object)

In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [44]:
coltras=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(coltras.fit_transform(x))
x

array([[0.0, 0.0, 0.0, 1.0, 27.0, 9, 51000],
       [1.0, 0.0, 0.0, 0.0, 29.0, 9, 48000],
       [0.0, 0.0, 0.0, 1.0, 30.0, 5, 52000],
       [1.0, 0.0, 0.0, 0.0, 25.0, 5, 66000],
       [0.0, 1.0, 0.0, 0.0, 48.0, 10, 68000],
       [0.0, 1.0, 0.0, 0.0, 33.0, 8, 51000],
       [0.0, 0.0, 1.0, 0.0, 33.0, 9, 69000],
       [1.0, 0.0, 0.0, 0.0, 40.0, 10, 79000],
       [0.0, 0.0, 0.0, 1.0, 38.0, 8, 68000],
       [0.0, 0.0, 1.0, 0.0, 35.0, 8, 38000],
       [0.0, 1.0, 0.0, 0.0, 28.0, 8, 56000],
       [0.0, 0.0, 1.0, 0.0, 35.0, 8, 72000],
       [1.0, 0.0, 0.0, 0.0, 36.5, 12, 79000],
       [0.0, 0.0, 0.0, 1.0, 31.0, 8, 85000],
       [0.0, 0.0, 1.0, 0.0, 37.0, 6, 49000],
       [0.0, 0.0, 0.0, 1.0, 40.0, 11, 69000],
       [0.0, 1.0, 0.0, 0.0, 50.0, 8, 68000],
       [0.0, 0.0, 0.0, 1.0, 31.0, 8, 68000],
       [0.0, 0.0, 0.0, 1.0, 36.5, 4, 68000],
       [0.0, 1.0, 0.0, 0.0, 41.0, 6, 75000],
       [0.0, 1.0, 0.0, 0.0, 29.0, 8, 70000]], dtype=object)

In [45]:
from sklearn.preprocessing import LabelEncoder
labelenc=LabelEncoder()
y=labelenc.fit_transform(y)
y


array([1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)


In [47]:
x_test

array([[0.0, 0.0, 0.0, 1.0, 38.0, 8, 68000],
       [0.0, 0.0, 0.0, 1.0, 31.0, 8, 85000],
       [0.0, 1.0, 0.0, 0.0, 29.0, 8, 70000],
       [1.0, 0.0, 0.0, 0.0, 29.0, 9, 48000],
       [0.0, 0.0, 1.0, 0.0, 35.0, 8, 72000],
       [0.0, 1.0, 0.0, 0.0, 28.0, 8, 56000]], dtype=object)

In [49]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_test[:,4:]=scaler.fit_transform(x_test[:,4:])
x_train[:,4:]=scaler.fit_transform(x_train[:,4:])

x_test



array([[0.0, 0.0, 0.0, 1.0, 1.7417271443536015, -0.44721359549995804,
        0.12681088516208938],
       [0.0, 0.0, 0.0, 1.0, -0.18333969940564224, -0.44721359549995804,
        1.5640009169991023],
       [0.0, 1.0, 0.0, 0.0, -0.7333587976225691, -0.44721359549995804,
        0.29589206537820856],
       [1.0, 0.0, 0.0, 0.0, -0.7333587976225691, 2.23606797749979,
        -1.5640009169991023],
       [0.0, 0.0, 1.0, 0.0, 0.9166984970282113, -0.44721359549995804,
        0.46497324559432773],
       [0.0, 1.0, 0.0, 0.0, -1.0083683467310323, -0.44721359549995804,
        -0.8876761961346256]], dtype=object)